### ISSUE TITLE
In dark mode the buttons are displayed

### ISSUE THREAD

**Issue by IngoManthey** [fgilde/MudExRichTextEditor#11]
I'm using MudBlazor 7.8.0. If I set the theme to dark, the buttons aren't visible. Does anyone have an idea what I can do?

**Comment by fgilde** [comment]
Sorry sorry sorry for really long delay. Didnt seen this entry. However i fixed it. Version 2.0.0 will be released next week. Again sorry.

**Comment by fgilde** [comment]
Solved [MudExRichTextEditor 2.0](https://www.nuget.org/packages/MudExRichTextEditor/2.0.0)
