### ISSUE TITLE
Security update is required

### ISSUE THREAD

**Issue by IngoManthey** [fgilde/MudExRichTextEditor#13]
The "SixLabors.ImageSharp" 3.1.4 package has a known high severity vulnerability, https://github.com/advisories/GHSA-63p8-c4ww-9cg7.
The "SixLabors.ImageSharp" 3.1.4 package has a known Moderate severity vulnerability, https://github.com/advisories/GHSA-qxrv-gp6x-rc23.
The System.Text.Encodings.Web 4.5.0 package has a known Critical severity vulnerability, https://github.com/advisories/GHSA-ghhp-997w-qr28.

**Comment by fgilde** [comment]
Is also fixed in version 2.0.0. This will released next week

**Comment by fgilde** [comment]
Solved [MudExRichTextEditor 2.0](https://www.nuget.org/packages/MudExRichTextEditor/2.0.0)
