### ISSUE TITLE
Unfortunately there is still a security gap.

### ISSUE THREAD

**Issue by IngoManthey** [fgilde/MudExRichTextEditor#14]
I have installed the update to version 2.0.1. Visual Studio alerts me to the following gap.

 Das Paket "System.Text.Encodings.Web" 4.5.0 weist eine bekannte Kritisch Schweregrad-Sicherheitsanfälligkeit auf, https://github.com/advisories/GHSA-ghhp-997w-qr28.

**Comment by fgilde** [comment]
I dont use System.Text.Encodings.Web neither in MudExRichTextEditor or MudBlazor.Extensions

**Comment by IngoManthey** [comment]
![Screenshot 2024-11-18 091512](https://github.com/user-attachments/assets/1f8db919-490a-4c79-bb36-d0fb36efacae)

you  do it.

**Comment by fgilde** [comment]
You're right, sorry for this. It was needed for a js Middleware for blazor server side apps. However I removed that you can use https://www.nuget.org/packages/MudExRichTextEditor/2.0.2
