### ISSUE TITLE
The mentions container shows up inside the editor only

### ISSUE THREAD

**Issue by americanslon** [fgilde/MudExRichTextEditor#5]
The mention container shows up inside the editor only. If you have a short editor or a long list, both are true in my case, it's essentially unusable. I tried playing around with z-index on various layers of the editor but nothing seems to work.

**Comment by fgilde** [comment]
Its solved in 1.0.6 https://www.nuget.org/packages/MudExRichTextEditor/1.0.6#readme-body-tab
