### ISSUE TITLE
Placeholder always displays when in read-only mode

### ISSUE THREAD

**Issue by gthoma2** [fgilde/MudExRichTextEditor#6]
As the title says - placeholder text overlaps the bound value. Only seems to happen when in read-only mode. Also HideeToolbarWhenReadOnly is also set to true:

You can see the text "Insert text here..." At the beginning of the contents:
![image001](https://github.com/fgilde/MudExRichTextEditor/assets/2625843/4188537c-fb5c-4547-b225-e5dd1c054370)

**Comment by fgilde** [comment]
thanks for reporting. Will fix it as soon as possible

**Comment by fgilde** [comment]
Its fixed in version [1.0.7](https://www.nuget.org/packages/MudExRichTextEditor/1.0.7)
