### ISSUE TITLE
Text size mismatch

### ISSUE THREAD

**Issue by dennisrahmen** [fgilde/MudExRichTextEditor#9]
Currently the Text sizes between the generated HTML of the editor and the one I get from MudBlazor are different.
So the "Normal" text from the Editor is way to small when being next to normal MudBlazor Text.

Is there a way to basically match the style of the MufBlazor Typo?

**Comment by fgilde** [comment]
Solved [MudExRichTextEditor 2.0](https://www.nuget.org/packages/MudExRichTextEditor/2.0.0)
